# Generated by Django 4.2.1 on 2023-07-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('AssetNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Asset_Name', models.CharField(max_length=50)),
                ('Asset_serialNumber', models.CharField(max_length=50, null=True)),
                ('Asset_Model', models.CharField(max_length=50, null=True)),
                ('Asset_type', models.CharField(max_length=50)),
                ('Asset_OS_Version', models.CharField(max_length=50, null=True)),
                ('Asset_Availability', models.BooleanField()),
                ('Asset_Ownership', models.CharField(max_length=50)),
                ('Asset_Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('ps_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=6)),
                ('Designation', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField()),
                ('LTIM_MailID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBorrowed', models.DateTimeField(null=True)),
                ('dateReturned', models.DateTimeField(null=True)),
                ('AssetNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.devices')),
                ('ps_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
        ),
    ]
