# Generated by Django 4.2.1 on 2023-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_Model',
            new_name='assetAvailability',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_Location',
            new_name='assetBrand',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_Name',
            new_name='assetLocation',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_OS_Version',
            new_name='assetModel',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='AssetNo',
            new_name='assetNo',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_serialNumber',
            new_name='assetOsVersion',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_Ownership',
            new_name='assetOwnership',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='Asset_type',
            new_name='assetType',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='Asset_Availability',
        ),
        migrations.AddField(
            model_name='devices',
            name='assetSerialNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='assetUpdate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='assetYear',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
