# Generated by Django 4.2.1 on 2023-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_asset_model_devices_assetavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='assetAvailability',
            field=models.CharField(default='Available', max_length=50, null=True),
        ),
    ]
