# Generated by Django 4.2.1 on 2023-11-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_devices_assetavailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicereport',
            old_name='AssetNo',
            new_name='assetNo',
        ),
    ]
