# Generated by Django 5.0 on 2023-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='end',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
