# Generated by Django 5.0 on 2024-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_calendar_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('ReleaseName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=20)),
                ('TestRail', models.CharField(max_length=100)),
                ('TestRaidId', models.CharField(max_length=20)),
                ('Build', models.CharField(max_length=100)),
                ('DefectLink', models.CharField(max_length=100)),
                ('Comment', models.JSONField(null=True)),
                ('TotalTC', models.IntegerField()),
                ('CurrentCount', models.JSONField(null=True)),
            ],
        ),
    ]
