# Generated by Django 5.0 on 2024-01-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
